apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  config.yaml: |
    {{- with .Values.moonraker.objects }}
    objects:
        {{- toYaml . | nindent 6 }}
    {{- end }}
