image:
  repository: ghcr.io/erickaby/moonraker-exporter
  tag:

port: 9101

moonraker:
  endpoint: http://localhost:7125
  objects:
    - name: extruder
      type: Extruder
    - name: heater_fan nozzle_cooling_fan
      type: Fan
    - name: heater_bed
      type: HeaterBed
    - name: fan
      type: Fan

printer:
  name: printer-01
